# Generated by Django 4.1.5 on 2023-03-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_app_label", models.CharField(max_length=255)),
                ("target_model_name", models.CharField(max_length=255)),
                ("target_slug", models.CharField(max_length=255)),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            ("DEBUG", 10),
                            ("INFO", 20),
                            ("SUCCESS", 25),
                            ("WARNING", 30),
                            ("ERROR", 40),
                        ]
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
            ],
        ),
    ]
