# Generated by Django 4.1.5 on 2023-03-27 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("systemlogs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemlog",
            name="target_app_label",
        ),
        migrations.RemoveField(
            model_name="systemlog",
            name="target_model_name",
        ),
        migrations.RemoveField(
            model_name="systemlog",
            name="target_slug",
        ),
        migrations.AddField(
            model_name="systemlog",
            name="content_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="systemlog",
            name="object_id",
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
