# Generated by Django 4.1.5 on 2023-03-27 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("systemlogs", "0002_remove_systemlog_target_app_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemlog",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
    ]
