# Generated by Django 4.1.7 on 2023-04-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("systemlogs", "0004_systemlog_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SystemLog",
        ),
    ]
