# Generated by Django 4.1.7 on 2023-05-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="Any external ID for this event.",
                max_length=255,
                null=True,
                verbose_name="External ID",
            ),
        ),
    ]
