# Generated by Django 4.1.7 on 2023-04-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_alter_source_url"),
        ("events", "0002_remove_event_end_remove_event_start_event_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="external_uuid",
        ),
        migrations.AddField(
            model_name="event",
            name="customers",
            field=models.BooleanField(
                default=False,
                help_text="Whether this event is affecting external customers.",
                verbose_name="Affects customers",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="Any external ID for this event.",
                max_length=255,
                null=True,
                verbose_name="External ID",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Any external URL for this event.",
                max_length=255,
                null=True,
                verbose_name="External URL",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="If the event is a singular point in time, leave the end date and time blank.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="If the source of his event is external, enter the source.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="services",
            field=models.ManyToManyField(
                blank=True, help_text="The services affected by this event.", to="services.service"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("backup", "Backup"),
                    ("configuration", "Configuration"),
                    ("deploy", "Deployment"),
                    ("deprovision", "Deprovision"),
                    ("downgrade", "Downgrade"),
                    ("incident", "Incident"),
                    ("maintenance", "Maintenance"),
                    ("migration", "Migration"),
                    ("patch", "Patch"),
                    ("provision", "Provision"),
                    ("reboot", "Reboot"),
                    ("release", "Release"),
                    ("restore", "Restore"),
                    ("rollback", "Rollback"),
                    ("scale", "Scale"),
                    ("snapshot", "Snapshot"),
                    ("upgrade", "Upgrade"),
                    ("other", "Other"),
                ],
                help_text="The type of event.",
                max_length=100,
            ),
        ),
    ]
