# Generated by Django 4.1.9 on 2023-05-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="Any external status for this event.",
                max_length=255,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Any external URL for this event.",
                max_length=255,
                null=True,
                verbose_name="URL",
            ),
        ),
    ]
