# Generated by Django 4.1.7 on 2023-04-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_time",
        ),
        migrations.AddField(
            model_name="event",
            name="end",
            field=models.DateTimeField(
                blank=True,
                help_text="If the event is a singular point in time, leave the end date and time blank.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="start",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
