# Generated by Django 4.1.7 on 2023-04-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_event_external_status_alter_event_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="source",
            new_name="external_source",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="url",
            new_name="external_url",
        ),
    ]
