# Generated by Django 4.1.7 on 2023-04-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_rename_external_source_event_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="Any external ID for this event.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="External ID",
            ),
        ),
    ]
