# Generated by Django 4.1.5 on 2023-03-06 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("service", models.CharField(choices=[("G", "GitHub")], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("S", "Software"),
                            ("H", "Hardware"),
                            ("N", "Network"),
                            ("L", "Logical"),
                            ("O", "Other"),
                        ],
                        max_length=1,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("owner", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "owning_team",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dependencies",
                    models.ManyToManyField(blank=True, to="services.service"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="src",
                        to="services.source",
                    ),
                ),
            ],
        ),
    ]
