# Generated by Django 4.1.5 on 2023-03-08 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="service",
            name="owning_team",
        ),
        migrations.AddField(
            model_name="service",
            name="metrics",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="oncalls",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="ownership",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="level",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.CharField(max_length=100),
        ),
    ]
