# Generated by Django 4.1.5 on 2023-03-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="path",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
