# Generated by Django 4.1.5 on 2023-03-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="level",
            new_name="priority",
        ),
    ]
