# Generated by Django 4.1.5 on 2023-03-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_remove_service_owner_remove_service_owning_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(default="example", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
