# Generated by Django 4.1.7 on 2023-05-02 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_source_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sources",
                to="services.organization",
            ),
        ),
    ]
