# Generated by Django 4.1.7 on 2023-04-18 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_rename_level_service_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="services.source",
            ),
        ),
    ]
