# Generated by Django 4.1.7 on 2023-05-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_source_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="url",
            field=models.CharField(
                default=None, max_length=100, unique=True, verbose_name="Organization URL"
            ),
            preserve_default=False,
        ),
    ]
