# Generated by Django 4.1.7 on 2023-05-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_organization_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="organization",
            name="url",
            field=models.CharField(max_length=255, unique=True, verbose_name="Organization URL"),
        ),
        migrations.AlterField(
            model_name="source",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.CharField(
                help_text="The URL to the repository on GitHub that contains the service catalog files.",
                max_length=255,
                unique=True,
                verbose_name="Repository URL",
            ),
        ),
    ]
