# Generated by Django 4.1.5 on 2023-03-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_rename_oncalls_service_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("schema", models.TextField()),
            ],
        ),
    ]
