# Generated by Django 4.1.7 on 2023-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_service_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.CharField(
                help_text="The URL to the repository on GitHub that contains the service catalog files.",
                max_length=100,
                verbose_name="Repository URL",
            ),
        ),
    ]
