# Generated by Django 4.1.9 on 2023-05-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_alter_organization_name_alter_organization_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="raw_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
