# Generated by Django 4.1.7 on 2023-04-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_alter_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
