# Generated by Django 4.1.5 on 2023-03-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="slug",
            field=models.SlugField(
                default="andymckay-beyond-cars", max_length=100, unique=True
            ),
            preserve_default=False,
        ),
    ]
