# Generated by Django 4.1.5 on 2023-03-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_source_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="source",
            old_name="service",
            new_name="host",
        ),
    ]
