# Generated by Django 4.1.7 on 2023-04-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_source_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.CharField(
                help_text="The URL to the repository on GitHub that contains the service catalog files.",
                max_length=100,
                unique=True,
                verbose_name="Repository URL",
            ),
        ),
    ]
