# Generated by Django 4.1.9 on 2023-05-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_organization_raw_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="raw_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
