# Generated by Django 4.1.5 on 2023-03-13 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_rename_service_source_host"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="metrics",
        ),
        migrations.RemoveField(
            model_name="service",
            name="ownership",
        ),
        migrations.RemoveField(
            model_name="service",
            name="support",
        ),
        migrations.AlterField(
            model_name="service",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="services.source",
            ),
        ),
    ]
