# Generated by Django 4.1.9 on 2023-05-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_service_raw_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
