# Generated by Django 4.1.7 on 2023-04-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_alter_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="events",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
