# Generated by Django 4.1.5 on 2023-03-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_remove_service_metrics_remove_service_ownership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="meta",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
