# Generated by Django 4.1.7 on 2023-04-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_service_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "auto_add_sources",
                    models.BooleanField(
                        default=True, help_text="Automatically add sources from the organization."
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
