# Generated by Django 4.1.5 on 2023-03-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_service_meta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="is_active",
            new_name="active",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="level",
            new_name="level",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="type",
            new_name="type",
        ),
    ]
