# Generated by Django 4.1.5 on 2023-03-24 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0010_rename_is_active_service_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="source",
            old_name="name",
            new_name="url",
        ),
        migrations.RemoveField(
            model_name="source",
            name="host",
        ),
        migrations.AddField(
            model_name="service",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="source",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="source",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
