# Generated by Django 4.1.7 on 2023-04-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcheck",
            name="slug",
            field=models.SlugField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
