# Generated by Django 4.1.10 on 2023-10-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_alter_service_type"),
        ("health", "0002_alter_checkresult_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="limit",
            field=models.CharField(
                choices=[("all", "All"), ("some", "Some"), ("none", "None")],
                default="all",
                help_text="How many services this check will be run against.",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="check",
            name="services",
            field=models.ManyToManyField(related_name="health_checks", to="services.service"),
        ),
    ]
