# Generated by Django 4.1.7 on 2023-04-18 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_healthcheck_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkresult",
            name="health_check",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="health.check"
            ),
            preserve_default=False,
        ),
    ]
