# Generated by Django 4.1.7 on 2023-04-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0006_alter_check_frequency_alter_checkresult_result_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="description",
            field=models.TextField(blank=True, help_text="Markdown is supported."),
        ),
        migrations.AlterField(
            model_name="check",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("ad-hoc", "Ad hoc"),
                ],
                default="daily",
                help_text="How often this check will be run.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="checkresult",
            name="result",
            field=models.CharField(
                choices=[
                    ("pass", "Pass"),
                    ("warning", "Warning"),
                    ("fail", "Fail"),
                    ("error", "Error"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="checkresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("timed-out", "Timed out"),
                    ("error", "Error"),
                    ("completed", "Completed"),
                ],
                default="sent",
                max_length=10,
            ),
        ),
    ]
